name: ci

on:
  pull_request:
    branches: [ main ]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: php-setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: xdebug
          extensions: xdebug

      - name: composer-validate
        run: composer validate

      - name: composer-cache
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.php-version }}-composer-

      - name: composer-install
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: php-cs-fixer
        run: vendor/bin/php-cs-fixer fix --dry-run --diff --verbose --ansi

      - name: phpstan
        run: vendor/bin/phpstan analyse --memory-limit 256M

      - name: phpunit
        env:
          FCM_OAUTH_TOKEN: ${{ secrets.FCM_OAUTH_TOKEN }}
          FCM_PROJECT_ID: ${{ secrets.FCM_PROJECT_ID }}
        run: vendor/bin/phpunit

      - name: coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./.coverage/coverage.xml
